import nodemailer from 'nodemailer'

function getTransporter() {
  return nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: Number(process.env.SMTP_PORT) || 465,
    secure: process.env.SMTP_SECURE === 'true',
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  })
}

export async function sendEmail({
  to, subject, html,
}: { to: string; subject: string; html: string }) {
  return getTransporter().sendMail({
    from: process.env.SMTP_FROM || process.env.SMTP_USER,
    to,
    subject,
    html,
  })
}

export function invoiceEmailTemplate(params: {
  clientName: string
  invoiceNo: string
  amount: number
  dueDate: string
  items: { description: string; total: number }[]
  companyName: string
  notes?: string
}) {
  const rows = params.items.map(i =>
    `<tr><td style="padding:8px 0;border-bottom:1px solid #f0f0f0">${i.description}</td><td style="padding:8px 0;border-bottom:1px solid #f0f0f0;text-align:right">$${i.total.toFixed(2)}</td></tr>`
  ).join('')
  return `
<!DOCTYPE html><html><body style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;color:#333">
<div style="background:#1d4ed8;padding:24px 32px"><h1 style="color:#fff;margin:0;font-size:24px">${params.companyName}</h1></div>
<div style="padding:32px">
  <h2 style="font-size:20px;margin:0 0 8px">Invoice ${params.invoiceNo}</h2>
  <p style="color:#666;margin:0 0 24px">Dear ${params.clientName},</p>
  <table style="width:100%;border-collapse:collapse">
    <thead><tr style="border-bottom:2px solid #e5e7eb"><th style="text-align:left;padding:8px 0;font-size:12px;text-transform:uppercase;color:#666">Description</th><th style="text-align:right;padding:8px 0;font-size:12px;text-transform:uppercase;color:#666">Amount</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <div style="text-align:right;margin-top:16px;padding-top:16px;border-top:2px solid #1d4ed8">
    <span style="font-size:18px;font-weight:bold">Total: $${params.amount.toFixed(2)} USD</span>
  </div>
  <div style="background:#fef9c3;padding:16px;border-radius:8px;margin-top:24px">
    <strong>Due Date:</strong> ${params.dueDate}<br>
    <strong>Payment:</strong> Bank Transfer
  </div>
  ${params.notes ? `<p style="color:#666;margin-top:16px">${params.notes}</p>` : ''}
</div>
<div style="background:#f9fafb;padding:16px 32px;font-size:12px;color:#999">This invoice was generated by ClientDesk.</div>
</body></html>`
}

export function reminderEmailTemplate(params: {
  clientName: string
  type: 'invoice' | 'service'
  details: string
  dueDate: string
  companyName: string
  companyEmail?: string
}) {
  return `
<!DOCTYPE html><html><body style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;color:#333">
<div style="background:#1d4ed8;padding:24px 32px"><h1 style="color:#fff;margin:0;font-size:24px">${params.companyName}</h1></div>
<div style="padding:32px">
  <h2 style="color:#dc2626">⚠️ Reminder: Action Required</h2>
  <p>Dear <strong>${params.clientName}</strong>,</p>
  <p>This is a friendly reminder regarding: <strong>${params.details}</strong></p>
  <p>Due/Expiry date: <strong>${params.dueDate}</strong></p>
  <p>Please take action before the due date to avoid service interruption.</p>
  <p>Contact us at ${params.companyEmail || ''} for assistance.</p>
</div>
<div style="background:#f9fafb;padding:16px 32px;font-size:12px;color:#999">Sent by ClientDesk — ${params.companyName}</div>
</body></html>`
}
